### ISSUE TITLE
GCP Cloud Function fails when loading google-cloud-bigquery library

### ISSUE THREAD

**Issue by miguel-andreu** [googleapis/python-bigquery#1170]
Hi everyone.

I'm facing a weird issue with an already working Cloud Function. Since the last update made today it was working perfectly, but now, we are not able to deploy the code.

#### Environment details

  - OS type and version: GCP Cloud Funcion, Server EU-WEST-3
  - Python version: `3.8`
  - pip version: default from CF
  - `google-cloud-bigquery` version: `2.7.0`

#### Steps to reproduce

  1. Build a Cloud Function
  2. Set as requeriments google-cloud-bigquery==2.7.0
  3. Add the following code 
  4. Set main as execution entry point

#### Code example

```python
from google.cloud import bigquery
from google.cloud import storage

def main(data, context):

    # Any code, the fail is producer when trying to import the library

```

#### Stack trace
```
Traceback (most recent call last): File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module> sys.exit(_cli()) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1128, in __call__ return self.main(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1053, in main rv = self.invoke(ctx) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 754, in invoke return __callback(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/_cli.py", line 37, in _cli app = create_app(target, source, signature_type) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 288, in create_app spec.loader.exec_module(source_module) File "<frozen importlib._bootstrap_external>", line 843, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/workspace/main.py", line 3, in <module> from mybigquery import MyBigQuery File "/workspace/mybigquery.py", line 3, in <module> from google.cloud import bigquery ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
Traceback (most recent call last): File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module> sys.exit(_cli()) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1128, in __call__ return self.main(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1053, in main rv = self.invoke(ctx) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 754, in invoke return __callback(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/_cli.py", line 37, in _cli app = create_app(target, source, signature_type) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 288, in create_app spec.loader.exec_module(source_module) File "<frozen importlib._bootstrap_external>", line 843, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/workspace/main.py", line 3, in <module> from mybigquery import MyBigQuery File "/workspace/mybigquery.py", line 3, in <module> from google.cloud import bigquery ImportError: cannot import name 'bigquery' from 'google.cloud' (unknown location)
```

Thanks in advance!

**Comment by miguel-andreu** [comment]
[SOLVED]

It has been solved by one/many/all of the following meassures (all were applied at the same)

- Removing specific versions from requeriment.txt and letting GCP to handle them
- Increasing the RAM memory from 512 to 1024 MB
- Downgrading Python from 3.8 to 3.7

**Comment by samarthg** [comment]
This is not working for me. Tried all of it, still getting import error. Is there any alternative to this library?

**Comment by meredithslota** [comment]
@samarthg If you are seeing similar errors, please open a new issue with repro steps. Thanks!
