### ISSUE TITLE
Getting error once running script over M1 OS "mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))"

### ISSUE THREAD

**Issue by tamerkadan1988** [googleapis/python-bigquery#1262]
Hi Team,

As people mentioned before, we are still having issues with M1 Apple to run such scripts.

am having this error : 

`Traceback (most recent call last):
  File "./vlapp", line 8, in <module>
    from google.cloud import bigquery
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/google/cloud/bigquery/client.py", line 59, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/google/cloud/bigquery_storage_v1/client.py", line 24, in <module>
    import google.api_core.gapic_v1.method
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/google/api_core/gapic_v1/__init__.py", line 16, in <module>
    from google.api_core.gapic_v1 import config
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/google/api_core/gapic_v1/config.py", line 23, in <module>
    import grpc
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/tamerz/Library/Python/3.8/lib/python/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/tamerz/Library/Python/3.8/lib/python/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so, 0x0002): tried: '/Users/tamerz/Library/Python/3.8/lib/python/site-packages/grpc/_cython/cygrpc.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-38-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-38-darwin.so' (no such file)
`
#### Environment details

  - OS type and version: 
  - Python version: `python --version` -> python3.8.5
  - pip version: `pip --version` -> pip3

##### 

gave the script the 777 chmod and also tried reinstall the python version + upgrade
Tried also installing the google package and uninstall it.
also tried those packages : 
pip install --no-binary :all: grpcio --ignore-installed
pip install --no-binary :all: grpcio-tools --ignore-installed

**Comment by tamerkadan1988** [comment]
#https://github.com/grpc/grpc/issues/28387

**Comment by pietrodn** [comment]
This is a breaking issue for Google Cloud's paying customers, and I guess many more developers using the libraries that depend on gRPC. It prevents developers working on Apple Silicon machines to install their dependencies correctly and get a working development environment.

An immediate action to alleviate the pain would be to "yank" the corrupted M1 wheel on PyPI, and avoid uploading it in future releases. That way, users could compile the library themselves.

With the CircleCI script I shared [here](https://github.com/grpc/grpc/issues/29262), it is possible to build proper Apple Silicon binary wheels, even from Linux. Given the severity of this issue for the developer experience, it would be a huge improvement even to build and upload those wheels by hand until proper automation is available.

**Comment by meredithslota** [comment]
Thank you so much for the report (and the referenced issue, which does seem at first glance to be the cause of this). I see both folks on this thread have commented the same on the linked issue (thank you again) so I'm going to see what I can do to escalate that issue internally.

**Comment by meredithslota** [comment]
There's a draft PR to fix this in the issue linked above; issue: https://github.com/grpc/grpc/issues/28387 PR: https://github.com/grpc/grpc/pull/29857 — please feel free to add feedback there!

**Comment by meredithslota** [comment]
The PR linked above looks like it's nearly ready for merging, stay tuned.

**Comment by meredithslota** [comment]
The latest release includes the fix: https://github.com/grpc/grpc/releases/tag/v1.47.0 — I'm going to keep this issue open until it's fully resolved but for folks on the thread, it should be possible to fix this by upgrading dependencies now. Please let us know if this doesn't fix the issue for you.

**Comment by da2nsch** [comment]
@meredithslota , this resolved it for me, thanks a lot! Really happy, wasn't able to develop locally with BQ for quite some time.

**Comment by loferris** [comment]
We've confirmed on our end that this issue is resolved on an M1 mac by making sure our versions of `google-cloud-bigquery` and `grpcio` are up-to-date. We'll close this issue after merging a PR that provides this fix for the BQ samples snippets, and the `requirements.txt` once merged should be a good example of a setup that works for that use-case!

**Comment by thuantv-vp** [comment]
> We've confirmed on our end that this issue is resolved on an M1 mac by making sure our versions of `google-cloud-bigquery` and `grpcio` are up-to-date. We'll close this issue after merging a PR that provides this fix for the BQ samples snippets, and the `requirements.txt` once merged should be a good example of a setup that works for that use-case!

The error is still repeated. I try everything base on stackoverflow but this error can not be fixed.

I have tried many approach but fail, the following method I have tried:

pip install --no-binary :all: grpcio --ignore-installed
pip install --no-binary :all: grpcio-tools --ignore-installed

pip install grpcio==1.47.0

pip install grpcio==1.49.1

I check with many people using Mac M1, they also meet the same issue.
